version: '3.8'

services:
  donnum-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DonnumMicroserviceDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - ServiceUrls__DonorService=http://host.docker.internal:8082
      - ReverseProxy__Clusters__donor-cluster__Destinations__destination1__Address=http://host.docker.internal:8082

networks:
  donnum-shared:
    external: true
    name: donnum-shared
